### PR TITLE
Updated hri logo with jpg image and increased width

### PR DESCRIPTION
**Pull request by praneethpr**

### CODE REVIEW

**Review by fightingtexasaggie — COMMENTED** [review]
aspect ratio gets changed with different browser screen sizes...there's some squish going on.

**Comment by praneethpr** [comment]
> aspect ratio gets changed with different browser screen sizes...there's some squish going on.

Could you post a screenshot?

**Review by mickel1138 — DISMISSED** [review]
Looks fine to me.

**Comment by fightingtexasaggie** [comment]
The aspect ratio of the photo isn't staying consistent, depending on browser size.

Screenshot from 2021-09-09 16-22-08
Screenshot from 2021-09-09 16-21-59
Screenshot from 2021-09-09 16-21-35
Screenshot from 2021-09-09 16-21-18
Screenshot from 2021-09-09 16-20-57

**Review by mickel1138 — APPROVED** [review]

**Pull request merged**
