### PR TITLE
Added identified status in the elastic config to not show all dataset…

### PR DESCRIPTION
**Pull request by praneethpr**
…s which do not have approved Difs

### CODE REVIEW

**Comment by mickel1138** [comment]
Is there a way to only index Identified?

**Comment by praneethpr** [comment]
> Is there a way to only index Identified?

We should add a check in the DatasetIndexSubscriber class, to only index datasets which are identified. But we use the same Class to populate both data-discovery and search index

**Comment by mickel1138** [comment]
> > Is there a way to only index Identified?
> 
> We should add a check in the DatasetIndexSubscriber class, to only index datasets which are identified. But we use the same Class to populate both data-discovery and search index

I looked around a bit, and you could use an Analyzer with a filter. But I think that's more complicated to configure.

**Comment by praneethpr** [comment]
> > > Is there a way to only index Identified?
> > 
> > 
> > We should add a check in the DatasetIndexSubscriber class, to only index datasets which are identified. But we use the same Class to populate both data-discovery and search index
> 
> I looked around a bit, and you could use an Analyzer with a filter. But I think that's more complicated to configure.

I think using a term filter is the simplest solution

**Comment by praneethpr** [comment]
> An exception has been thrown during the rendering of a template ("Could not find the entry "app" in "/home/mwilliamson/pelagos/public/build/entrypoints.json". Found: entrypoints.").
> 
> is this just my environment, or can anyone else confirm?

Did you clear the cache? I'm unable to reproduce this error

**Comment by mickel1138** [comment]
> > An exception has been thrown during the rendering of a template ("Could not find the entry "app" in "/home/mwilliamson/pelagos/public/build/entrypoints.json". Found: entrypoints.").
> > is this just my environment, or can anyone else confirm?
> 
> Did you clear the cache? I'm unable to reproduce this error

That's usually when you forgot `yarn dev`

**Pull request merged**
